### ISSUE TITLE
NoClassDefFoundError: com.parse.TwitterAuthenticationProvider

### ISSUE THREAD

**Issue by wangbourne** [ParsePlatform/ParseUI-Android#100]
I have included 
compile 'com.parse:parseui-login-android:0.0.1'
compile 'com.parse:parseui-widget-android:0.0.1'
compile 'com.parse.bolts:bolts-android:1.2.1'
compile 'com.facebook.android:facebook-android-sdk:4.0.1'
compile 'com.parse:parse-android:1.10.1'

but still get the error of:
java.lang.NoClassDefFoundError: com.parse.TwitterAuthenticationProvider
                                                                                             at com.parse.ParseTwitterUtils.getAuthenticationProvider(ParseTwitterUtils.java:19)
                                                                                             at com.parse.ParseTwitterUtils.initialize(ParseTwitterUtils.java:50)

**Comment by wangmengyan95** [comment]
You need to include ParseTwitterUtils if you need twitter login. Add `compile 'com.parse:parsetwitterutils-android:1.10.3'` to your project's dependencies will solve the problem.
