### ISSUE TITLE
Performing stop of activity that is not resumed

### ISSUE THREAD

**Issue by TonyTangAndroid** [ParsePlatform/ParseUI-Android#12]
Sometimes I would experience this issue:

ActivityThread﹕ Performing stop of activity that is not resumed: {SampleDispatchActivity}
    java.lang.RuntimeException: Performing stop of activity that is not resumed: {SampleDispatchActivity}
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3133)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3220)
            at android.app.ActivityThread.access$1100(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1223)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

I am using Nexus 5 With Android 4.4.4. Would it be addressed?

**Comment by pansx1215** [comment]
有可能是你的程序没有找到入口的Activity。请查看一下入口的Activity代码是否执行了。
我出现了这个错误，是因为我在if else判断中，没有执行入口的Activity！

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wangmengyan95** [comment]
Hello guys, this issue has not been updated for a long time, I will close this issue right now. If any of you still have problems, please reopen it.

**Comment by hisham2007** [comment]
I faced the issue today on nexus 4 running Android 22
