### ISSUE TITLE
Import project vs dependencies

### ISSUE THREAD

**Issue by vokvince** [ParsePlatform/ParseUI-Android#125]
Hello !

Reading the documentation I don't understand how I can added this library(ParseUI-Android). 

Few month ago I imported the lib with the repository's project(and today I have a crash because the new ParseUser() doesn't work) so I switch for the dependencies but we can't override ParseSignUpFragment and there is still this crash...

The crash : 
FATAL EXCEPTION: main
                                                                 java.lang.IllegalArgumentException: You must create this type of ParseObject using ParseObject.create() or the proper subclass.
                                                                     at com.parse.ParseObject.<init>(ParseObject.java:365)
                                                                     at com.parse.ParseObject.<init>(ParseObject.java:334)
                                                                     at com.parse.ParseUser.<init>(ParseUser.java:162)
                                                                     at com.parse.ui.ParseSignupFragment.onClick(ParseSignupFragment.java:178)
                                                                     at android.view.View.performClick(View.java:4763)
                                                                     at android.view.View$PerformClick.run(View.java:19821)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5272)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

Could you help me please ? 

Thank you  !

**Comment by wangmengyan95** [comment]
Hi @vokvince, could you tell us whcih Parse version are you using?

**Comment by vokvince** [comment]
Hello @wangmengyan95 ,

My build.gradle root project use : com.parse:parse-android:1.12.0

Currently I'm using the ParseUI-Login, I'm not confident because I make some modification.
So I'm forced to modify the code and if there is a new version of ParseUI-Login, I should copy this modification. it's a little bit old school :)
My project work with this solution but I'm not satisfied.

When I used the UI login library I included com.parse:parseui-login-android:0.0.1 but I had the crash with the ParseObject.create() as described in github.

This library doesn't have callbacks ? For exemple, I would like to customize a field error or add my own font. It seems that it's very static.... The only thing I can do is to override the layouts ?

Thank you for your help and for your recommendation,

**Comment by wangmengyan95** [comment]
Hi @vokvince, I tried our LoginSample with the dependencies and it works without exception. Here is my dependencies
```
dependencies {
    compile 'com.facebook.android:facebook-android-sdk:4.9.0'
    compile 'com.parse:parseui-login-android:0.0.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.parse:parse-android:1.12.0'
    compile 'com.parse:parsefacebookutils-v4-android:1.10.4@aar'
    compile 'com.parse:parsetwitterutils-android:1.10.4'
}
```

**Comment by wangmengyan95** [comment]
Hi @vokvince, we have noticed the issue you mentioned. If you use maven to import the library, you lose the ability to easily config the library. Right now our target is to make developers easy to config the library even they use maven. 
I understand your suggestion about font, could you tell me more about the customize a field error?
Thanks

**Comment by vokvince** [comment]
Hi @wangmengyan95 ,

For the customization I would like to get more callbacks(errror, sucesss) on the fields. And more flexibility for the font of the view and for the loader components. It will be a good start :)
Have you plan to improve the lib ?

Thx !
